force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer Name</label>
    <referenceTo>Employer__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employer__c/Employer__c.object-meta.xml
<CustomObject>
    <label>Employer</label>
    <nameField>
        <label>Employer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employer__c/fields/Highest_Salary__c.field-meta.xml
<CustomField>
    <fullName>Highest_Salary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Highest Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employer__c/fields/Least_Salary__c.field-meta.xml
<CustomField>
    <fullName>Least_Salary__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Least Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmployeeHelper.cls
public with sharing class EmployeeHelper {
    public static void updateMinAndMaxSalary(List<Employee__c> newEmployees, Map<Id, Employee__c> oldEmployeesMap){

        Set<Id> employerIds = new Set<Id>();

        //Loop to get the EmployerId of all the new employee records or the updated employee records where there is a change in the Employer or Salary
        for(Employee__c emp : newEmployees){
            if(oldEmployeesMap == null && emp.Employer__c != null){
                employerIds.add(emp.Employer__c);
            }
            else if(oldEmployeesMap != null && emp.Employer__c != null &&( (emp.Employer__c != oldEmployeesMap.get(emp.Id).Employer__c) || (emp.Salary__c != oldEmployeesMap.get(emp.Id).Salary__c))){
                employerIds.add(emp.Employer__c);
                employerIds.add(oldEmployeesMap.get(emp.Id).Employer__c);
            }
        }

        Map<Id, List<Decimal>> employerToSalaryMap = new Map<Id, List<Decimal>>();

        List<Employer__c> employersToBeUpdated = new List<Employer__c>();
        //Aggregate result to get the Min, Max Salary for each employer

        if(!employerIds.isEmpty()){
            for(AggregateResult empAgg : [SELECT Employer__c employerId, MIN(Salary__c) minSal, MAX(Salary__c) maxSal
                                        FROM Employee__c 
                                        WHERE Employer__c IN :employerIds
                                        GROUP BY Employer__c]){
                employerToSalaryMap.put((Id)empAgg.get('employerId'), new List<Decimal>{(Decimal)empAgg.get('maxSal'),(Decimal)empAgg.get('minSal')});                                                                                 
            }

            for(Id employerId : employerIds){
                Employer__c employer = new Employer__c (Id = employerId, 
                                                    Highest_Salary__c = employerToSalaryMap.get(employerId)[0],
                                                    Least_Salary__c = employerToSalaryMap.get(employerId)[1]);
                employersToBeUpdated.add(employer);                                                                       
            }
        }

        if(!employersToBeUpdated.isEmpty()){
            update employersToBeUpdated;
        }
    }
}